//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Pk_id { get; set; }
        public string Userid { get; set; }
        public int Rating1 { get; set; }
        public string Feedback { get; set; }
    }
}
