//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public int pk_id { get; set; }
        public string Name { get; set; }
        public string Wave { get; set; }
        public string Skills { get; set; }
        public string Trainings { get; set; }
        public string Certifications { get; set; }
        public string ImgUrl { get; set; }
    }
}
